# document_intelligence_wrapper/__init__.py

from .document_intelligence_client import DocumentIntelligenceClientWrapper
from .extractors.extract_utils import table_markdown,extract_page_text
from .extractors.text_extractor import analyze_document_text
